# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0002_auto_20161126_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceline',
            name='is_positive',
            field=models.BooleanField(default=False),
        ),
    ]
