# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 01:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saas', '0003_balanceline_is_positive'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='card_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='created_by',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
