# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-21 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0004_auto_20161221_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='extra',
            field=models.TextField(null=True),
        ),
    ]
