# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-07 15:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0007_0_3_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecharge',
            name='quota',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='balanceline',
            name='selector',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='charge',
            name='amount',
            field=models.PositiveIntegerField(default=0, help_text='total amount in cents (i.e. 100ths) of unit'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='created_at',
            field=models.DateTimeField(help_text='date/time of creation in ISO format'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='description',
            field=models.TextField(help_text='description for the Charge as appears on billing statements', null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='exp_date',
            field=models.DateField(help_text='expiration date of the credit card used'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='last4',
            field=models.PositiveSmallIntegerField(help_text='last 4 digits of the credit card used'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'done'), (3, 'disputed'), (2, 'failed'), (0, 'created')], default=0, help_text="current state ('created', 'done', 'failed', 'disputed')"),
        ),
        migrations.AlterField(
            model_name='charge',
            name='unit',
            field=models.CharField(default='usd', help_text='three-letter ISO 4217 code for currency unit (ex: usd)', max_length=3),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.SlugField(help_text='unique identifier per provider, typically used in URLs'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='date/time of creation in ISO format'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True, help_text='free-form text description for the Coupon', null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='ends_at',
            field=models.DateTimeField(blank=True, help_text='date/time in ISO format at which the code expires to purchase subscriptions', null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='nb_attempts',
            field=models.IntegerField(blank=True, help_text='number of times the coupon can be used', null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='organization',
            field=models.ForeignKey(help_text='coupon will only apply to purchased plans from this provider', on_delete=django.db.models.deletion.CASCADE, to='saas.Organization'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='percentage discounted', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='coupon will only apply to this plan', null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.Plan'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date/time of creation in ISO format'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='default_timezone',
            field=models.CharField(default='America/Chicago', max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Organization name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='postal_code',
            field=models.CharField(max_length=50, verbose_name='Zip/Postal Code'),
        ),
        migrations.AlterField(
            model_name='roledescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date/time of creation in ISO format'),
        ),
        migrations.AlterField(
            model_name='roledescription',
            name='slug',
            field=models.SlugField(help_text='Unique identifier, typically used in URLs.'),
        ),
        migrations.AlterField(
            model_name='roledescription',
            name='title',
            field=models.CharField(help_text='Short description of the role. Grammatical rules to pluralize the title might be used in User Interfaces.', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(help_text='date/time of creation in ISO format'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='descr',
            field=models.TextField(default='N/A', help_text='free-form text description for the Transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='dest_account',
            field=models.CharField(default='unknown', help_text='target account to which funds are deposited', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='dest_amount',
            field=models.PositiveIntegerField(default=0, help_text='amount deposited into target in dest_unit'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='dest_organization',
            field=models.ForeignKey(help_text='target Organization to which funds are deposited', on_delete=django.db.models.deletion.PROTECT, related_name='incoming', to='saas.Organization'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='dest_unit',
            field=models.CharField(default='usd', help_text='three-letter ISO 4217 code for target currency unit (ex: usd)', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='event_id',
            field=models.SlugField(help_text='Event at the origin of this transaction"        " (ex. subscription, charge, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='orig_account',
            field=models.CharField(default='unknown', help_text='source account from which funds are withdrawn', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='orig_amount',
            field=models.PositiveIntegerField(default=0, help_text='amount withdrawn from source in orig_unit'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='orig_organization',
            field=models.ForeignKey(help_text='source Organization from which funds are withdrawn', on_delete=django.db.models.deletion.PROTECT, related_name='outgoing', to='saas.Organization'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='orig_unit',
            field=models.CharField(default='usd', help_text='three-letter ISO 4217 code for source currency unit (ex: usd)', max_length=3),
        ),
    ]
