# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-29 22:46
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0007_0_3_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecharge',
            name='quota',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
