# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-19 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0008_0_3_4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='last_name',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full name of the person that will benefit from the subscription (GroupBuy)', max_length=150, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'created'), (2, 'failed'), (1, 'done'), (3, 'disputed')], default=0, help_text='Current state (i.e. created, done, failed, disputed)'),
        ),
    ]
