# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-11 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0009_auto_20181210_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(2, 'failed'), (0, 'created'), (1, 'done'), (3, 'disputed')], default=0, help_text='Current state (i.e. created, done, failed, disputed)'),
        ),
    ]
