# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-22 01:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0009_0_3_5'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='picture',
            field=models.URLField(blank=True, help_text='Profile picture', max_length=2083, null=True, verbose_name='Profile picture'),
        ),
    ]
