# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-22 01:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0009_0_3_5'),
    ]

    operations = [
    ]
