# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-25 12:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0010_0_4_0'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='interval',
            new_name='period_type',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='transaction_fee',
            new_name='broker_fee_percent',
        ),
        migrations.RenameField(
            model_name='chargeitem',
            old_name='invoiced_fee',
            new_name='invoiced_processor_fee',
        ),
        migrations.AddField(
            model_name='chargeitem',
            name='invoiced_broker_fee',
            field=models.ForeignKey(help_text='Fee transaction to broker in order to process the transaction invoiced through this charge', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoiced_broker_fee_item', to='saas.Transaction'),
        ),
    ]
