# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-20 17:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0011_0_7_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='roledescription',
            name='implicit_create_on_none',
            field=models.BooleanField(default=False, help_text='Automatically adds the role when a user and profile share the same e-mail domain.'),
        ),
    ]
