# Generated by Django 2.2.13 on 2021-02-14 12:18

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0013_0_9_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='nb_renewal_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Number of successive failed charges'),
        ),
    ]
