# Generated by Django 3.2.18 on 2023-06-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0016_v0_15_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_personal',
            field=models.BooleanField(default=False, help_text='True when the plan is meant for personal profiles first and foremost'),
        ),
    ]
