# Generated by Django 3.2.18 on 2023-08-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0017_v1_0_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='ends_at',
            field=models.DateTimeField(blank=True, help_text='Date/time when the role ends', null=True),
        ),
        migrations.RenameField(
            model_name='agreement',
            old_name='modified',
            new_name='updated_at',
        ),
    ]
