# Generated by Django 3.2.18 on 2023-08-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0017_v1_0_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='ends_at',
            field=models.DateTimeField(blank=True, help_text='Date/time when the role ends', null=True),
        ),
        migrations.AlterField(
            model_name='advancediscount',
            name='length',
            field=models.PositiveSmallIntegerField(default=1, help_text='Contract length associated with the period (defaults to 1)'),
        ),
    ]
