# Generated by Django 3.2.20 on 2023-10-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0018_v0_17_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecharge',
            name='maximum_limit',
            field=models.PositiveIntegerField(default=0, null=True),
        )
    ]
