# Generated by Django 3.2.23 on 2024-02-14 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0019_v0_18_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='roledescription',
            name='otp_required',
            field=models.BooleanField(default=False, help_text='Requires users with the role to sign-in using an OTP code as a multi-factor authentication.'),
        ),
    ]
