# Generated by Django 3.2.23 on 2024-02-14 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0019_v0_18_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='roledescription',
            name='otp_required',
            field=models.BooleanField(default=False, help_text='Requires users with the role to sign-in using an OTP code as a multi-factor authentication.'),
        ),
        migrations.AlterField(
            model_name='advancediscount',
            name='length',
            field=models.PositiveSmallIntegerField(default=1, help_text='Contract length associated with the period (defaults to 1)'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='slug',
            field=models.SlugField(help_text='Unique identifier shown in the URL bar', unique=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='title',
            field=models.CharField(help_text='Short description of the agreement', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date/time the agreement was last updated (in ISO format)'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='claim_code',
            field=models.SlugField(blank=True, help_text='Code used to assign the cart item to a user in group buy', null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(help_text='Long description of the plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='title',
            field=models.CharField(help_text='Short description of the plan', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usecharge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date/time of creation (in ISO format)'),
        ),
        migrations.AlterField(
            model_name='usecharge',
            name='description',
            field=models.TextField(help_text='Long description of the use charge'),
        ),
        migrations.AlterField(
            model_name='usecharge',
            name='maximum_limit',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of use charge added per period before notififying subscriber', null=True),
        ),
        migrations.AlterField(
            model_name='usecharge',
            name='plan',
            field=models.ForeignKey(help_text='Plan the use chage is related to', on_delete=django.db.models.deletion.CASCADE, related_name='use_charges', to='saas.plan'),
        ),
        migrations.AlterField(
            model_name='usecharge',
            name='quota',
            field=models.PositiveIntegerField(default=0, help_text='Number of use charge included in the plan'),
        ),
        migrations.AlterField(
            model_name='usecharge',
            name='slug',
            field=models.SlugField(help_text='Unique identifier shown in the URL bar', unique=True),
        ),
        migrations.AlterField(
            model_name='usecharge',
            name='title',
            field=models.CharField(help_text='Short description of the use charge', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usecharge',
            name='use_amount',
            field=models.PositiveIntegerField(default=0, help_text='Amount of the use charge in plan currency unit'),
        ),
    ]
