# Generated by Django 4.2.27 on 2026-02-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0021_v1_0_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='no_implicit_role',
            field=models.BooleanField(default=False, help_text='The profile does not allow implicit roles'),
        ),
    ]
